"""ratings, title imdb id

Revision ID: 34ff102b0a83
Revises: 5bd8a6d2a67e
Create Date: 2026-09-27 16:09:26.752968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ff102b0a83'
down_revision: Union[str, Sequence[str], None] = '5bd8a6d2a67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('imdb', sa.Double(), nullable=True),
    sa.Column('imdb_votes', sa.Integer(), nullable=True),
    sa.Column('rt_critic', sa.Integer(), nullable=True),
    sa.Column('rt_audience', sa.Integer(), nullable=True),
    sa.Column('metacritic', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tmdb_id', 'media_type')
    )
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imdb_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_column('imdb_id')

    op.drop_table('ratings')
    # ### end Alembic commands ###
