"""user taste prompt dismissed

Revision ID: 3a3d3bfa724b
Revises: f3b61fbd81da
Create Date: 2026-09-27 21:09:47.471097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3d3bfa724b'
down_revision: Union[str, Sequence[str], None] = 'f3b61fbd81da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taste_prompt_dismissed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('taste_prompt_dismissed_at')

    # ### end Alembic commands ###
