"""initial schema

Revision ID: 3f920262b6c8
Revises: 
Create Date: 2026-09-27 14:13:51.698429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f920262b6c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_tmdb_id'), ['tmdb_id'], unique=False)

    op.create_table('plex_items',
    sa.Column('rating_key', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('match_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('rating_key')
    )
    op.create_table('show_facts',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('confirmed', sa.String(), nullable=True),
    sa.Column('pending', sa.String(), nullable=True),
    sa.Column('pending_seen', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tmdb_id', 'key')
    )
    op.create_table('titles',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('backdrop_path', sa.String(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('networks', sa.JSON(), nullable=False),
    sa.Column('seasons', sa.JSON(), nullable=False),
    sa.Column('last_episode', sa.JSON(), nullable=True),
    sa.Column('next_episode', sa.JSON(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('poll_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tmdb_id', 'media_type')
    )
    op.create_table('users',
    sa.Column('plex_id', sa.BigInteger(), nullable=False),
    sa.Column('pms_account_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('plex_id'),
    sa.UniqueConstraint('pms_account_id')
    )
    op.create_table('follows',
    sa.Column('plex_id', sa.BigInteger(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plex_id'], ['users.plex_id'], ),
    sa.PrimaryKeyConstraint('plex_id', 'tmdb_id')
    )
    op.create_table('plays',
    sa.Column('history_key', sa.String(), nullable=False),
    sa.Column('plex_id', sa.BigInteger(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('rating_key', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plex_id'], ['users.plex_id'], ),
    sa.PrimaryKeyConstraint('history_key')
    )
    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plays_plex_id'), ['plex_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plays_tmdb_id'), ['tmdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plays_viewed_at'), ['viewed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plays_viewed_at'))
        batch_op.drop_index(batch_op.f('ix_plays_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_plays_plex_id'))

    op.drop_table('plays')
    op.drop_table('follows')
    op.drop_table('users')
    op.drop_table('titles')
    op.drop_table('show_facts')
    op.drop_table('plex_items')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_events_detected_at'))

    op.drop_table('events')
    # ### end Alembic commands ###
