"""taste: use_for_picks, poster; chat mentions are 'mentioned'

Revision ID: 421524f75d74
Revises: 55ba17fd99f7
Create Date: 2026-09-27 16:36:11.022776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421524f75d74'
down_revision: Union[str, Sequence[str], None] = '55ba17fd99f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taste_signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_for_picks', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('poster_path', sa.String(), nullable=True))

    # ### end Alembic commands ###
    # Chat mentions imported before explicit "told" existed were never statements of taste.
    op.execute("UPDATE taste_signals SET source = 'mentioned' WHERE source = 'plexbot'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taste_signals', schema=None) as batch_op:
        batch_op.drop_column('poster_path')
        batch_op.drop_column('use_for_picks')

    # ### end Alembic commands ###
