"""taste signals, imdb import rows

Revision ID: 55ba17fd99f7
Revises: 34ff102b0a83
Create Date: 2026-09-27 16:31:09.484974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ba17fd99f7'
down_revision: Union[str, Sequence[str], None] = '34ff102b0a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imdb_rows',
    sa.Column('plex_id', sa.BigInteger(), nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('title_type', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('noted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('match', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['plex_id'], ['users.plex_id'], ),
    sa.PrimaryKeyConstraint('plex_id', 'imdb_id', 'kind')
    )
    op.create_table('taste_signals',
    sa.Column('plex_id', sa.BigInteger(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('noted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plex_id'], ['users.plex_id'], ),
    sa.PrimaryKeyConstraint('plex_id', 'tmdb_id', 'media_type', 'source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taste_signals')
    op.drop_table('imdb_rows')
    # ### end Alembic commands ###
