"""sign-in, watchlist, library, recommendations, renewal checks

Revision ID: 5bd8a6d2a67e
Revises: 9c47caf44b3a
Create Date: 2026-09-27 15:03:50.877304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd8a6d2a67e'
down_revision: Union[str, Sequence[str], None] = '9c47caf44b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('rating_key', sa.String(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tmdb_id', 'media_type')
    )
    op.create_table('renewal_checks',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('tmdb_id')
    )
    op.create_table('feedback',
    sa.Column('plex_id', sa.BigInteger(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plex_id'], ['users.plex_id'], ),
    sa.PrimaryKeyConstraint('plex_id', 'tmdb_id', 'media_type')
    )
    op.create_table('recommendations',
    sa.Column('plex_id', sa.BigInteger(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Double(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('backdrop_path', sa.String(), nullable=True),
    sa.Column('overview', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('because', sa.JSON(), nullable=False),
    sa.Column('trending', sa.Boolean(), nullable=False),
    sa.Column('in_library', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plex_id'], ['users.plex_id'], ),
    sa.PrimaryKeyConstraint('plex_id', 'tmdb_id', 'media_type')
    )
    op.create_table('watchlist_items',
    sa.Column('plex_id', sa.BigInteger(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plex_id'], ['users.plex_id'], ),
    sa.PrimaryKeyConstraint('plex_id', 'tmdb_id', 'media_type')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plex_token_enc', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('signed_in_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('overseerr_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('overseerr_id')
        batch_op.drop_column('signed_in_at')
        batch_op.drop_column('plex_token_enc')

    op.drop_table('watchlist_items')
    op.drop_table('recommendations')
    op.drop_table('feedback')
    op.drop_table('renewal_checks')
    op.drop_table('library')
    # ### end Alembic commands ###
