"""identity links, link codes, alerts

Revision ID: 9c47caf44b3a
Revises: 3f920262b6c8
Create Date: 2026-09-27 14:37:14.913310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c47caf44b3a'
down_revision: Union[str, Sequence[str], None] = '3f920262b6c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('discord_name', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pin_id', sa.BigInteger(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('alert_prefs',
    sa.Column('plex_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_enabled', sa.Boolean(), nullable=False),
    sa.Column('ntfy_topic', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plex_id'], ['users.plex_id'], ),
    sa.PrimaryKeyConstraint('plex_id')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plex_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['plex_id'], ['users.plex_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plex_id', 'event_id', 'channel')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_plex_id'), ['plex_id'], unique=False)

    op.create_table('identity_links',
    sa.Column('surface', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('plex_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plex_id'], ['users.plex_id'], ),
    sa.PrimaryKeyConstraint('surface', 'external_id')
    )
    with op.batch_alter_table('identity_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_links_plex_id'), ['plex_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_links_plex_id'))

    op.drop_table('identity_links')
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_plex_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_event_id'))

    op.drop_table('deliveries')
    op.drop_table('alert_prefs')
    op.drop_table('link_codes')
    # ### end Alembic commands ###
