"""trending picks

Revision ID: 9f732b36d602
Revises: 421524f75d74
Create Date: 2026-09-27 18:34:24.463422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f732b36d602'
down_revision: Union[str, Sequence[str], None] = '421524f75d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trending_picks',
    sa.Column('plex_id', sa.BigInteger(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Double(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('backdrop_path', sa.String(), nullable=True),
    sa.Column('overview', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('in_library', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plex_id'], ['users.plex_id'], ),
    sa.PrimaryKeyConstraint('plex_id', 'tmdb_id', 'media_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trending_picks')
    # ### end Alembic commands ###
