"""watch entries

History (history.py): a person's own ratings and statuses. Everything they had "told" Telly
they liked moves here as Liked it (switched off: unrated), and the `told` taste signals go.

Revision ID: dffa73df0f12
Revises: 492e70d4bb96
Create Date: 2026-09-28 18:37:05.814536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dffa73df0f12'
down_revision: Union[str, Sequence[str], None] = '492e70d4bb96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_entries',
    sa.Column('plex_id', sa.BigInteger(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('backdrop_path', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plex_id'], ['users.plex_id'], ),
    sa.PrimaryKeyConstraint('plex_id', 'tmdb_id', 'media_type')
    )
    # ### end Alembic commands ###
    op.execute("""
        INSERT INTO watch_entries (plex_id, tmdb_id, media_type, title, poster_path, rating,
                                   status, source, added_at, updated_at)
        SELECT t.plex_id, t.tmdb_id, t.media_type, COALESCE(t.title, ''), t.poster_path,
               CASE WHEN t.use_for_picks THEN 1 END, NULL,
               CASE WHEN EXISTS (SELECT 1 FROM plays p WHERE p.plex_id = t.plex_id
                                 AND p.tmdb_id = t.tmdb_id AND p.media_type = t.media_type)
                    THEN 'plex' ELSE 'manual' END,
               COALESCE(t.noted_at, CURRENT_TIMESTAMP), CURRENT_TIMESTAMP
        FROM taste_signals t WHERE t.source = 'told'
    """)
    # a Plex title with nothing said about it is no row at all (history._tidy)
    op.execute("DELETE FROM watch_entries WHERE source = 'plex' AND rating IS NULL AND status IS NULL")
    op.execute("DELETE FROM taste_signals WHERE source = 'told'")


def downgrade() -> None:
    """Downgrade schema. Liked and loved go back to `told`; the rest of History is lost."""
    op.execute("""
        INSERT OR IGNORE INTO taste_signals (plex_id, tmdb_id, media_type, source, title, noted_at,
                                             use_for_picks, poster_path)
        SELECT plex_id, tmdb_id, media_type, 'told', title, added_at, 1, poster_path
        FROM watch_entries WHERE rating >= 1
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watch_entries')
    # ### end Alembic commands ###
